/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.syntrex;

/**
 *
 * @author g.boone
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class gestaoFuncionarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestaoFuncionarios.class.getName());

    /**
     * Creates new form gestaoFuncionarios
     */
    

public class TelaCadastroFuncionario extends JFrame {

    private JTextField campoColaborador;
    private JTextField matriculaField;
    private JTextField funcaoField;

    public TelaCadastroFuncionario() {
        setTitle("Cadastrar Funcionário");
        setSize(800, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
        getContentPane().setBackground(new Color(25, 47, 104)); // azul escuro

        // Ícone de perfil (menu dropdown)
        JButton perfilButton = new JButton("\uD83D\uDC64");
        perfilButton.setBounds(740, 10, 40, 30);
        perfilButton.setBackground(null);
        perfilButton.setBorder(null);
        perfilButton.setForeground(Color.WHITE);
        perfilButton.setFont(new Font("SansSerif", Font.PLAIN, 22));

        JPopupMenu perfilMenu = new JPopupMenu();
        JMenuItem perfilItem = new JMenuItem("Perfil do Usuário");
        JMenuItem sairItem = new JMenuItem("Sair");

        perfilMenu.add(perfilItem);
        perfilMenu.add(sairItem);

        perfilButton.addActionListener(e -> perfilMenu.show(perfilButton, 0, perfilButton.getHeight()));

        sairItem.addActionListener(e -> System.exit(0));
        perfilItem.addActionListener(e -> JOptionPane.showMessageDialog(this, "Acessando perfil..."));

        // Botão Voltar
        JButton voltarButton = new JButton("← VOLTAR");
        voltarButton.setBounds(20, 50, 120, 30);
        voltarButton.setBackground(null);
        voltarButton.setBorder(null);
        voltarButton.setForeground(Color.WHITE);
        voltarButton.setFont(new Font("SansSerif", Font.BOLD, 14));
        voltarButton.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, "Voltando...");
        });

        // Título
        JLabel titulo = new JLabel("Cadastrar Funcionário");
        titulo.setBounds(250, 100, 400, 30);
        titulo.setForeground(Color.WHITE);
        titulo.setFont(new Font("SansSerif", Font.BOLD, 24));

        // Labels e campos
        JLabel nomeLabel = new JLabel("Nome do colaborador");
        nomeLabel.setBounds(100, 160, 200, 25);
        nomeLabel.setForeground(Color.WHITE);

        nomeField = new JTextField();
        nomeField.setBounds(300, 160, 400, 30);

        JLabel matriculaLabel = new JLabel("Matricula");
        matriculaLabel.setBounds(100, 210, 200, 25);
        matriculaLabel.setForeground(Color.WHITE);

        matriculaField = new JTextField();
        matriculaField.setBounds(300, 210, 400, 30);

        JLabel funcaoLabel = new JLabel("Função");
        funcaoLabel.setBounds(100, 260, 200, 25);
        funcaoLabel.setForeground(Color.WHITE);

        funcaoField = new JTextField();
        funcaoField.setBounds(300, 260, 400, 30);

        // Botão salvar
        JButton salvarButton = new JButton("SALVAR");
        salvarButton.setBounds(350, 320, 100, 35);
        salvarButton.setBackground(new Color(0, 153, 119));
        salvarButton.setForeground(Color.WHITE);
        salvarButton.setFocusPainted(false);
        salvarButton.addActionListener(e -> salvarFuncionario());

        // Adiciona tudo no frame
        add(perfilButton);
        add(voltarButton);
        add(titulo);
        add(nomeLabel);
        add(nomeField);
        add(matriculaLabel);
        add(matriculaField);
        add(funcaoLabel);
        add(funcaoField);
        add(salvarButton);
    }

    private void salvarFuncionario() {
        String nome = nomeField.getText();
        String matricula = matriculaField.getText();
        String funcao = funcaoField.getText();

        // Aqui você pode inserir no banco de dados
        JOptionPane.showMessageDialog(this, "Salvo:\nNome: " + nome + "\nMatricula: " + matricula + "\nFunção: " + funcao);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new TelaCadastroFuncionario().setVisible(true));
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        syntrexSimbolo = new javax.swing.JLabel();
        iconeBoneco = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        txtcadastroFuncionario = new javax.swing.JLabel();
        txtnomefuncionario = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JLabel();
        txtfuncao = new javax.swing.JLabel();
        campoColaborador = new javax.swing.JTextField();
        campoFuncao = new javax.swing.JTextField();
        campoMatricula = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1, 1));

        jPanel1.setBackground(new java.awt.Color(34, 55, 115));

        syntrexSimbolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/syntrex simbolo.png"))); // NOI18N

        iconeBoneco.setBackground(new java.awt.Color(34, 55, 115));
        iconeBoneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/boneco.png"))); // NOI18N
        iconeBoneco.setBorderPainted(false);

        voltar.setBackground(new java.awt.Color(34, 55, 115));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/voltar.png"))); // NOI18N
        voltar.setBorderPainted(false);

        txtcadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/txt cadastrar funcionario.png"))); // NOI18N

        txtnomefuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/txt nome do colaborador.png"))); // NOI18N

        txtmatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/txt matricula.png"))); // NOI18N

        txtfuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/txt funcao.png"))); // NOI18N

        campoColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoColaboradorActionPerformed(evt);
            }
        });

        campoFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFuncaoActionPerformed(evt);
            }
        });

        campoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMatriculaActionPerformed(evt);
            }
        });

        salvar.setBackground(new java.awt.Color(34, 55, 115));
        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/syntrex/imagens/botao salvar.png"))); // NOI18N
        salvar.setBorderPainted(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(txtcadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(660, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnomefuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addComponent(campoMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addComponent(campoColaborador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(syntrexSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeBoneco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconeBoneco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(syntrexSimbolo))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(txtcadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtnomefuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoFuncao)
                    .addComponent(txtfuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(salvar)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarActionPerformed

    private void campoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMatriculaActionPerformed

    private void campoFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFuncaoActionPerformed

    private void campoColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoColaboradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gestaoFuncionarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoColaborador;
    private javax.swing.JTextField campoFuncao;
    private javax.swing.JTextField campoMatricula;
    private javax.swing.JButton iconeBoneco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel syntrexSimbolo;
    private javax.swing.JLabel txtcadastroFuncionario;
    private javax.swing.JLabel txtfuncao;
    private javax.swing.JLabel txtmatricula;
    private javax.swing.JLabel txtnomefuncionario;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
